version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: lms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
